spring.application.name=ApiGateway

### Configuracion de Spring Cloud Gateway

#
# URIs internas en la red Docker (todos los microservicios exponen puerto 8080 internamente)
api-gw-tpback.url-microservicio-transporte=http://ms-transporte:8080
api-gw-tpback.url-microservicio-solicitudtransporte=http://ms-solicitudtransporte:8080
api-gw-tpback.url-microservicio-logistica=http://ms-logistica:8080

# Puerto expuesto del Gateway
server.port=9000

# Configuracion para Swagger UI agregado en Gateway (agrega entradas para cada microservicio)
springdoc.swagger-ui.urls[0].name=Transporte
springdoc.swagger-ui.urls[0].url=http://ms-transporte:8080/v3/api-docs
springdoc.swagger-ui.urls[1].name=SolicitudTransporte
springdoc.swagger-ui.urls[1].url=http://ms-solicitudtransporte:8080/v3/api-docs
springdoc.swagger-ui.urls[2].name=Logistica
springdoc.swagger-ui.urls[2].url=http://ms-logistica:8080/v3/api-docs

# Opcional: path del swagger-ui mapper
springdoc.swagger-ui.path=/swagger-ui.html
